# Generated by Django 4.1.3 on 2022-12-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctorname', models.CharField(max_length=50)),
                ('Speciality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=50)),
                ('L_name', models.CharField(max_length=20)),
                ('Claim', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Dos', models.CharField(max_length=60)),
                ('Appointment_Time', models.CharField(max_length=60)),
                ('Doctor_name', models.CharField(max_length=50)),
                ('Speciality', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Action1', models.CharField(max_length=50)),
            ],
        ),
    ]
