# Generated by Django 4.1.3 on 2022-12-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelupload',
            old_name='Dos',
            new_name='DOS',
        ),
    ]
