# Generated by Django 4.1.3 on 2022-12-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0005_excelupload_doa_frontdeskmodel_doa'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontdeskmodel',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
