# Generated by Django 4.1.3 on 2022-12-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0007_frontdeskmodel_status_alter_frontdeskmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelupload',
            name='DOS',
            field=models.DateField(),
        ),
    ]
